project_name: leavegroups

before:
  hooks:
    - go mod tidy

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64

archives:
  - builds:
      - leavegroups
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x86_64

signs:
  - artifacts: checksum
    args:
      [
        "--batch",
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
